# Generated by Django 5.2.3 on 2025-06-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_cart_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
    ]
