# Generated by Django 5.2.3 on 2025-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_cart_products_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='carts', to='shop_app.product'),
        ),
    ]
