# Generated by Django 5.2 on 2025-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_description_mymodel_address_mymodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
