# Generated by Django 5.2 on 2025-06-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
