# Generated by Django 5.2.3 on 2025-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=255)),
                ('total_patient', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
